name = "typeracer-worker"  # Name of your Worker scriptname = "typeracer-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurableObject" }
]

[[kv_namespaces]]
binding = "ROOM_STATE"
id = "886fe4f8471d48c5ab6c24f001eb7add"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomDurableObject"]